//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class a1
    {
        public a1()
        {
            this.b1 = new HashSet<b1>();
        }
    
        public int a { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<b1> b1 { get; set; }
    }
}
